name: Auto commit

on:

  push:
    branches:
      - main
      
  schedule:
  - cron: "0 6 * * *" # See https://crontab.guru/#0_7,9,11,17,20_*_*_*

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          set -o pipefail
          git config --local user.email "mrtampan54@gmail.com"
          git config --local user.name "mrtampan"
          git add -A
          
          arr[0]="chore(bot): 😂 auto commit haha"
          arr[1]="chore(bot): 😱 auto commit waduh"
          arr[2]="chore(bot): 👿 auto commit"
          arr[3]="chore(bot): 💩 auto commit"
          arr[4]="chore(bot): 🙏 auto commit"
          arr[5]="chore(bot): 🙈 auto commit"
          arr[6]="chore(bot): 🐐 auto commit mbekk"
          arr[7]="chore(bot): 🤖 auto commit tektek"
          arr[8]="chore(bot): 🟩 auto commit"
          arr[9]="chore(bot): 👻 auto commit hihi"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          force: true
          directory: "."
          github_token: ${{ secrets.TOKEN }}
